### ISSUE TITLE
Create resource manager

### ISSUE THREAD

**Issue by stabor705** [AGH-Code-Industry/archimedes#17]
- Research resource management in game engines
- Maybe find some examples? It shouldn't be an overwhelmingly large system.
- Design a solution. What we will most probably want is most probably a system that manages mapping between unique identifiers and resources (such as textures, models, sounds etc.), interfaces with file system, ensures that only one copy of resource exists in memory at a given moment, manages resources lifecycles etc.
- ~~Maybe read about Virtual File Systems? It is a popular technology with actual game engines.~~ (maybe nah, we don't need it since cross-platform filesystem access is in standard library)
- The issue of how to generically refer to a resource has to be resolved. Maybe use some templates such as Resource\<Texture\>, ...?

**Comment by Challmymind** [comment]
Moved to #66.
